# Change these first
owner: jovita-s # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: TEST-GEOPORTAL
    url: https://www.geoportal.lt
  - name: Foninis žemėlapis
    url: https://www.geoportal.lt/mapproxy/gisc_pagrindinis/MapServer/tile/11/14532/21046
  - name: test-down-service
    url: https://vlkiis.lki.lt/gis/app/gisproxy.ashx/rest/services/LKIIS/Tarmes/MapServer/export?dpi=96&transparent=true&format=png8&layers=show%3A0&bbox=509904.0057917094%2C6175386.471634376%2C510281.8315473609%2C6175911.935185304&bboxSR=3346&imageSR=3346&size=714%2C993&f=image
  - name: WMS.ORT10LT-WM
    url: https://www.geoportal.lt/wss/service/NZT-ORT10LT_recent-wm-WMS/httpauth/licid-LGII-4b6ccc8b-1a4a-4d86-ae5f-d993613361a0
    headers:
      - "Authorization: Basic $USERNAME:$PASSWORD"


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: 
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/jovita-s/uptime-monitor/refs/heads/master/assets/map-svgrepo-com.svg
  faviconSvg: https://raw.githubusercontent.com/jovita-s/uptime-monitor/refs/heads/master/assets/map-svgrepo-com.svg
  name: Servisų monitoringas (Test)
  introTitle: "**Šiame puslapyje pateikiama informacija apie stebimų paslaugų veikimą.**"
  introMessage: "Tai yra testinis servisų stebėsenos puslapis, pateikiantis **realaus laiko** duomenis iš mūsų [GitHub repozitorijos](https://github.com/jovita-s/uptime-monitor). Puslapis sukurtas naudojant Upptime atviro kodo sprendimą paslaugų stebėsenai, kuris naudoja: GitHub Actions, GitHub Issues ir GitHub Pages funkcionalumą."
  navbar:
    - title: Status
      href: /uptime-monitor
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Geoportal
      href: https://www.geoportal.lt/
  theme: light
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
